config/routes.rb
Urssflat::Application.routes.draw do

  devise_for :users

  get "users/home"
  get "users/index"
  get '/users/:id', to: 'users#show', as: :user

  resources :flats do 
    resources :bookings
  end
  resources :tags

  root 'pages#home'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flat
  belongs_to :booker, class_name: "User"
  validates :start_date, :end_date, presence: true
  validate :start_date_before_end_date?
  def total_days
  	(self.end_date - self.start_date)/3600/24
  end

  def total_price
  	self.flat.day_price * total_days
  end

  def start_date_before_end_date?
  	if self.end_date < self.start_date
  		errors.add(:end_date, "can't be in the past")
  	end
  end

end

app/models/flat.rb
class Flat < ActiveRecord::Base
	belongs_to :owner, class_name: "User"
	has_and_belongs_to_many :tags
	
	has_many :pictures
	accepts_nested_attributes_for :pictures

	has_many :bookings
	has_many :bookers, through: :bookings
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :flat
	has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :flats
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :flats, foreign_key: "owner_id"
  has_many :bookings, foreign_key: "booker_id"
  has_many :booked_flats, through: :bookings, source: :flat

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :full_name, presence: true
  validates :telephone, numericality: { only_integer: true }, length: { is: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!, except: [:home]

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :full_name << :telephone << :avatar
    devise_parameter_sanitizer.for(:account_update) << :full_name << :telephone << :avatar
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @flat = Flat.find(params[:flat_id])
    @total_price = @booking.total_price
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @flat = Flat.find(params[:flat_id])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = current_user.bookings.build(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to flat_booking_path(@booking.flat.id, @booking.id), notice: 'Booking was successfully created.' }
        format.json { render action: 'show', status: :created, location: @booking }
      else
        format.html do 
          flash[:error] = "Invalid booking : dates fordbidden"
          
          redirect_to new_flat_booking_path(@booking.flat.id)
        end
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to users_home_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :flat_id, :booker_id)
    end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  before_action :lookup_tags, only: [:new, :edit]
  before_action :lookup_owner, only: [:edit, :show]

  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
    @picture = @flat.pictures.build
  end

  # GET /flats/1/edit
  def edit
    @picture = @flat.pictures.last
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = current_user.flats.create(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flat }
      else
        format.html { render action: 'new' }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to users_home_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:title, :adress, :day_price, :description, pictures_attributes: [:id, :file], tag_ids: [])
    end

  def lookup_tags
    @tags = Tag.all
  end

  def lookup_owner
    @user = @flat.owner
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  end

  def index

  end


  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking, url: flat_bookings_path) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :flat_id, :as => :hidden, :input_html => { :value => @flat.id } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Flat</th>
      <th>Booker</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        <td><%= booking.flat %></td>
        <td><%= booking.booker %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @booking.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @booking.end_date %>
</p>

<p>
  <strong>Flat:</strong>
  <%= @booking.flat.title %>
</p>

<p>
  <strong>Total Price:</strong>
  <%= @total_price %> €
</p>

<p>
  <strong>Booker:</strong>
  <%= @booking.booker.full_name %>
</p>

app/views/flats/_form.html.erb
<%= form_for(@flat) do |f| %>
  <% if @flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
      <% @flat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_area :adress %>
  </div>
  <div class="field">
    <%= f.label :day_price %><br>
    <%= f.number_field :day_price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
  </div>
  <div class="field">
  <%= f.fields_for :pictures, @picture do |pf| %>
    <%= pf.file_field :file %>
  <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render 'form' %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<h1>Listing flats</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Adress</th>
      <th>Day price</th>
      <th>Description</th>
      <th>Owner</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.title %></td>
        <td><%= flat.adress %></td>
        <td><%= flat.day_price %></td>
        <td><%= flat.description %></td>
        <td><%= flat.owner.full_name %></td>
        <td><%= link_to 'Show', flat %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render 'form' %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @flat.title %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @flat.adress %>
</p>

<p>
  <strong>Day price:</strong>
  <%= @flat.day_price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flat.description %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @flat.owner.full_name %>
</p>

<p>
  <strong>Flat commidities:</strong>
  <% @flat.tags.each do |tag| %>
  <%= tag.name + " " %>
  <% end %>
</p>

<p>
  <strong>Flat photos:</strong>
  <br><br>
  <% @flat.pictures.each do |picture| %>
  <%= image_tag picture.file.url(:medium) %>
  <% end %>
</p>

<p>
  <% unless @flat.owner == current_user %>
    <%= link_to "Book this appartment", new_flat_booking_path(@flat), class: "btn btn-default" %>
  <% end %>
</p>

<p> <% if @flat.owner == current_user %>
  <%= link_to 'Edit', edit_flat_path(@flat) %>
  <%= link_to 'Delete', flat_path(@flat), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Urssflat</title>
 <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">

<!-- Optional theme -->
	<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->

  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="assets/logo.jpg"> URSS Flat</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
         </div>
           <button type="submit" class="btn btn-default">Submit</button>
       </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "List your gulags", new_flat_path %></li>
        <li><%= link_to "See more than #{Flat.count} gulags", flats_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
              <%= current_user.full_name %> <b class="caret"></b>
             </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My profile", users_home_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <%= link_to "sign in", new_user_session_path %>   
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="container"> 
  <!-- <div class="alert alert-danger"><%= flash[:error] %></div -->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> 
	<%= yield %>
</div>

<%= javascript_include_tag "application" %>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/home.html.erb
<h1>COUCOU</h1>

app/views/users/home.html.erb
<h1>Hello, <%= current_user.full_name %> !</h1>

<h2>My information :</h2>

<p> 
	<%= image_tag current_user.avatar.url(:medium) %>
	<br>Email: <%= current_user.email %>
	<br>Telephone: <%= current_user.telephone %>
</p>

<p>
	<%= link_to 'Edit your information', edit_user_registration_path %>
</p>

<h2>My Gulags:</h2>

<p>
<table class="table table-striped">
	<tbody>
	<% current_user.flats.each do |flat| %>
		<tr>
			<td><%= flat.title %></td>
			<td><%= link_to 'Show', flat_path(flat) %></td>
			<td><%= link_to 'Edit', edit_flat_path(flat) %></tb>
			<td><%= link_to 'Delete', flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
    </tbody>
</table>
</p>

<h2>My bookings:</h2>
<p>
<table class="table table-striped">
	<tbody>
	<% current_user.bookings.each do |booking| %>
		<tr>
			<td><%= booking.start_date %></td>
			<td><%= booking.end_date %></td>
			<td><%= booking.flat.title %></td>
			<td><%= link_to 'Show', flat_booking_path(booking.flat_id, booking.id) %></td>
			<td><%= link_to 'Delete', flat_booking_path(booking.flat_id, booking.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
    </tbody>
</table>
</p>

app/views/users/index.html.erb
<h1> Voici la liste de tous les users de notre super site !</h1>

<p>
	<% User.all.each do |user| %>
		<div>
			<%=  user.full_name %>
			<%= link_to "show", user_path(user) %>
		</div>
	<% end %>
</p>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>


<table class="table table-striped">
  <tbody>
	<% @user.bookings.each do |booking| %>
	  <tr>
	    <td><%= booking.flat.title %></td>
	    <td><%= booking.flat.adress %></td>
	    <td><%= booking.flat.day_price %> € per day</td>
	    <td><%= booking.start_date %></td>
	    <td><%= booking.end_date %></td>
	    <td>
	    </td>
	  </tr>
	<% end %>
  </tbody>
</table>